[toolchain]
anchor_version = "0.31.0"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "HyrodCdYTKX4TFPpDpuH8pDVb2cKmzkn824btBf1DmvY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx create-codama-client.ts; npx tsx --test --no-warnings tests/*.ts"
